<?php

namespace App\Enums;

enum RolesEnum: string
{
    case SUPERADMIN = 'ROLE_USUARIO_SUPER_ADMIN';
    case ADMIN_REPORTE = 'ROLE_USUARIO_ADMIN_REPORTE';
    case SUPERVISOR_REPORTE = 'ROLE_USUARIO_SUPERVISOR_REPORTE';
    case EMPLEADO = 'ROLE_USUARIO_EMPLEADO';
    case USUARIO = 'ROLE_USUARIO_BASE';
}
